# Generated by Django 4.1.5 on 2023-02-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default=' ', max_length=100)),
                ('reason', models.CharField(default=' ', max_length=200)),
            ],
        ),
    ]
