# Generated by Django 4.1.5 on 2023-02-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveReq', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavereq',
            name='name',
        ),
        migrations.AddField(
            model_name='leavereq',
            name='nameEp',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
