# Generated by Django 4.1.5 on 2023-02-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveReq', '0002_remove_leavereq_name_leavereq_nameep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavereq',
            name='email',
            field=models.TextField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='leavereq',
            name='nameEp',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
