# Generated by Django 4.1.5 on 2023-02-04 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='epdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default=' ', max_length=100)),
                ('mobile', models.IntegerField(default=' ', max_length=200)),
                ('gender', models.TextField(default='', max_length=100)),
                ('specialization', models.TextField(default=' ', max_length=100)),
                ('religion', models.TextField(default=' ', max_length=100)),
                ('Blood', models.TextField(default=' ', max_length=100)),
                ('role', models.TextField(default=' ', max_length=100)),
                ('salary', models.TextField(default=' ', max_length=100)),
                ('joining', models.TextField(default=' ', max_length=100)),
                ('duration', models.TextField(default='', max_length=100)),
            ],
        ),
    ]
