# Generated by Django 4.1.5 on 2023-01-31 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adminSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.CharField(default='', max_length=200)),
                ('phone', models.IntegerField(max_length=11)),
                ('password', models.TextField(max_length=20)),
            ],
        ),
    ]
